# Generated by Django 5.1.7 on 2025-04-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.AddField(
            model_name='faq',
            name='area',
            field=models.CharField(default='LD', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_images/'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
