# Generated by Django 5.1.7 on 2025-04-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_remove_faq_created_at_faq_area_faq_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='reference',
            field=models.URLField(blank=True, help_text='관련 문서 또는 웹 링크 (선택)', max_length=300, null=True),
        ),
    ]
